server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://WastemanagerAdmin:Test@127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: WASTE-MANAGER-CORE
          uri: lb://WASTE-MANAGER-CORE
          predicates:
            - Path=/waste-manager-core/**
        - id: WASTE-MANAGER-ADDRESS
          uri: lb://WASTE-MANAGER-ADDRESS
          predicates:
            - Path=/waste-manager-address/**

  eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

